package com.phyo.food_management_system.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@DynamoDBTable(tableName = "menus")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Menu {

    @DynamoDBHashKey(attributeName = "menu_id")
    @DynamoDBAutoGeneratedKey
    private String menuId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "restaurantId_index")
    private String restaurantId;
    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "price")
    private Double price;
}
