package com.phyo.food_management_system.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.phyo.food_management_system.util.LocalDateTimeConverter;
import com.phyo.food_management_system.util.OrderItemListConverter;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;

@DynamoDBTable(tableName = "orders")
@Data
public class Order {

    @DynamoDBHashKey(attributeName = "order_id")
    @DynamoDBAutoGeneratedKey
    private String orderId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userId_index")
    private String userId;

    @DynamoDBAttribute(attributeName = "restaurant_id")
    private String restaurantId;

    @DynamoDBAttribute(attributeName = "items")
    @DynamoDBTypeConverted(converter = OrderItemListConverter.class)
    private List<OrderItem> items;

    @DynamoDBAttribute(attributeName = "total_price")
    private Double totalPrice;

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTypeConvertedEnum
    private OrderStatus status;

    @DynamoDBAttribute(attributeName = "created_at")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute(attributeName = "updated_at")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime updatedAt;
}

