package com.phyo.food_management_system.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@DynamoDBTable(tableName = "users")
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @DynamoDBHashKey(attributeName = "user_id")
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute(attributeName = "user_name") // Optional: specifies the attribute name in DynamoDB
    private String username;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email_index")
    private String email;

    @DynamoDBAttribute(attributeName = "password") // Optional: specifies the attribute name in DynamoDB
    private String password;

    @DynamoDBAttribute(attributeName = "role") // Optional: specifies the attribute name in DynamoDB
    @DynamoDBTypeConvertedEnum
    private Role role;

}